import { UserRole } from './userProfile';

export type AskVisibility =
  | 'public'
  | 'members_only'
  | 'verified_only'
  | 'targeted'
  | 'selected_users'
  | 'ghost';

export type AskStatus =
  | 'draft'
  | 'published'
  | 'closed'
  | 'Active'
  | 'Draft'
  | 'Paused'
  | 'Closed';

export interface EcosystemAsk {
  id: string;

  creatorId: string;
  creatorName?: string;
  creatorRole: UserRole;
  creatorAvatar?: string;
  creatorTagline?: string;
  creatorLocation?: string;
  creatorStage?: string;
  creatorVerified?: boolean;

  category: string;
  type?: string; // backwards compatibility

  title: string;
  shortSummary: string;
  description: string;
  desiredOutcome: string;

  categoryData: Record<string, any>;

  targeting: {
    userTypes: string[];
    industries?: string[];
    geography?: string[];
  };

  visibility: AskVisibility;

  responseActions: string[];

  attachments?: {
    pitchDeck?: boolean;
    elevatorPitch?: boolean;
    financialSnapshot?: boolean;
    ddLocker?: boolean;
    otherDocuments?: boolean;
  };

  deadline?: string | null;

  status: AskStatus;

  createdAt: string;
  updatedAt: string;

  // Backwards compatibility fields
  dateCreated?: string;
  requirement?: string;
  targetUserType?: string;
  responsesCount?: number;
}

export interface AskFieldOption {
  value: string;
  label: string;
}

export type AskFieldType =
  | 'text'
  | 'textarea'
  | 'select'
  | 'multi_select'
  | 'number'
  | 'currency'
  | 'date'
  | 'boolean'
  | 'radio'
  | 'tags'
  | 'calculated';

export interface AskFieldConfig {
  id: string;
  label: string;
  type: AskFieldType;
  required?: boolean;
  placeholder?: string;
  helperText?: string;
  options?: AskFieldOption[] | string[];
  defaultValue?: any;
  halfWidth?: boolean;
  notice?: string;
  dependsOn?: {
    field: string;
    value: any;
  };
}

export interface AskCategoryConfig {
  id: string;
  label: string;
  description: string;
  titlePlaceholder: string;
  defaultTargetUserTypes: string[];
  responseActions: string[];
  fields: AskFieldConfig[];
}

export interface AskRoleConfig {
  role: UserRole;
  roleLabel: string;
  categories: Record<string, AskCategoryConfig>;
  categoryOrder: string[];
}

export const VISIBILITY_OPTIONS: Array<{
  value: AskVisibility;
  label: string;
  description: string;
  badge: string;
}> = [
  {
    value: 'public',
    label: 'Public',
    description: 'Visible to everyone on the Xentro ecosystem and search directories.',
    badge: 'Open Access',
  },
  {
    value: 'members_only',
    label: 'Xentro Members Only',
    description: 'Visible exclusively to logged-in and registered Xentro users.',
    badge: 'Platform Members',
  },
  {
    value: 'verified_only',
    label: 'Verified Users Only',
    description: 'Accessible only by KYC-verified founders, accredited investors, and verified mentors.',
    badge: 'KYC Verified',
  },
  {
    value: 'targeted',
    label: 'Target User Types Only',
    description: 'Shown only in the feeds of users matching your specified target audience.',
    badge: 'Role Targeted',
  },
  {
    value: 'selected_users',
    label: 'Selected Users',
    description: 'Direct distribution only to approved connections or shortlisted partners.',
    badge: 'Curated Access',
  },
  {
    value: 'ghost',
    label: 'Ghost Mode (Stealth)',
    description: 'Anonymizes company / person name and logo. Details revealed only after mutual acceptance.',
    badge: 'Stealth / Anonymized',
  },
];

// ==========================================
// 1. STARTUP ASK CONFIGURATION (10 Categories, NO GRANTS)
// ==========================================
const STARTUP_ASK_CATEGORIES: Record<string, AskCategoryConfig> = {
  investment: {
    id: 'investment',
    label: 'Investment',
    description: 'Raise capital for your round with structured terms, valuation, and instruments.',
    titlePlaceholder: 'e.g. Raising ₹1.5 Cr Pre-Seed Round for Enterprise AI Orchestration',
    defaultTargetUserTypes: ['Investor'],
    responseActions: [
      'Express Interest',
      'Request Meeting',
      'Request Pitch Deck',
      'Request DD Locker',
      'Send Message',
    ],
    fields: [
      {
        id: 'fundingStage',
        label: 'Funding Stage',
        type: 'select',
        required: true,
        halfWidth: true,
        options: [
          'Pre-Seed',
          'Seed',
          'Seed+',
          'Pre-Series A',
          'Series A',
          'Series B',
          'Series C',
          'Series D+',
          'Growth Stage',
          'Bridge Round',
          'Strategic Round',
          'Other',
        ],
      },
      {
        id: 'currency',
        label: 'Currency',
        type: 'select',
        required: true,
        halfWidth: true,
        defaultValue: 'INR',
        options: ['INR', 'USD', 'EUR', 'GBP', 'Other'],
      },
      {
        id: 'totalRoundSize',
        label: 'Total Round Size',
        type: 'currency',
        required: true,
        halfWidth: true,
        placeholder: 'e.g. 15000000',
        helperText: 'Total target capital for this round',
      },
      {
        id: 'amountCommitted',
        label: 'Amount Already Committed',
        type: 'currency',
        halfWidth: true,
        placeholder: 'e.g. 3000000',
        helperText: 'Capital already wired or in signed term sheets',
      },
      {
        id: 'amountRemaining',
        label: 'Amount Remaining',
        type: 'calculated',
        halfWidth: true,
        helperText: 'Auto-calculated: Total Round Size - Amount Already Committed',
      },
      {
        id: 'fundraisingStatus',
        label: 'Fundraising Status',
        type: 'select',
        required: true,
        halfWidth: true,
        options: [
          'Preparing to Raise',
          'Round Open',
          'Actively Raising',
          'Partially Committed',
          'Lead Investor Secured',
          'Final Allocation Remaining',
          'Round Closed',
        ],
      },
      {
        id: 'roundOpenDate',
        label: 'Round Open Date',
        type: 'date',
        halfWidth: true,
      },
      {
        id: 'targetClosingDate',
        label: 'Target Round Closing Date',
        type: 'date',
        required: true,
        halfWidth: true,
      },
      {
        id: 'investmentInstruments',
        label: 'Investment Instruments',
        type: 'multi_select',
        required: true,
        options: [
          'Equity Shares',
          'Preference Shares',
          'CCPS',
          'SAFE',
          'iSAFE',
          'Convertible Note',
          'CCD',
          'Venture Debt',
          'Revenue-Based Financing',
          'Strategic Equity',
          'Other',
          'Open to Discussion',
        ],
      },
      {
        id: 'minCheque',
        label: 'Minimum Cheque Size',
        type: 'currency',
        halfWidth: true,
        placeholder: 'e.g. 1000000',
      },
      {
        id: 'preferredCheque',
        label: 'Preferred Cheque Size',
        type: 'currency',
        halfWidth: true,
        placeholder: 'e.g. 2500000',
      },
      {
        id: 'maxCheque',
        label: 'Maximum Cheque Size',
        type: 'currency',
        halfWidth: true,
        placeholder: 'e.g. 5000000',
      },
      {
        id: 'hasLeadInvestor',
        label: 'Lead Investor Secured?',
        type: 'select',
        halfWidth: true,
        options: ['Yes', 'No', 'Open to Both'],
        defaultValue: 'No',
      },
      {
        id: 'targetLeadAmount',
        label: 'Target Lead Investment Amount',
        type: 'currency',
        halfWidth: true,
        placeholder: 'e.g. 5000000',
        dependsOn: { field: 'hasLeadInvestor', value: 'Yes' },
      },
      {
        id: 'valuationStatus',
        label: 'Valuation Status',
        type: 'select',
        halfWidth: true,
        options: [
          'Valuation Decided',
          'Under Discussion',
          'Open to Negotiation',
          'Not Disclosing',
          'Not Applicable',
        ],
      },
      {
        id: 'preMoneyValuation',
        label: 'Pre-Money Valuation',
        type: 'currency',
        halfWidth: true,
        placeholder: 'e.g. 100000000',
        dependsOn: { field: 'valuationStatus', value: 'Valuation Decided' },
      },
      {
        id: 'postMoneyValuation',
        label: 'Post-Money Valuation',
        type: 'currency',
        halfWidth: true,
        placeholder: 'e.g. 115000000',
        dependsOn: { field: 'valuationStatus', value: 'Valuation Decided' },
      },
      {
        id: 'equityOffered',
        label: 'Equity Offered (%)',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. 10% - 15%',
        dependsOn: { field: 'valuationStatus', value: 'Valuation Decided' },
      },
      {
        id: 'useOfFunds',
        label: 'Use of Funds Categories',
        type: 'multi_select',
        options: [
          'Product Development',
          'Technology',
          'Research & Development',
          'Hiring',
          'Sales',
          'Marketing',
          'Customer Acquisition',
          'Operations',
          'Manufacturing',
          'Inventory',
          'Market Expansion',
          'Regulatory / Compliance',
          'Working Capital',
          'International Expansion',
          'Other',
        ],
      },
      {
        id: 'useOfFundsDescription',
        label: 'Use of Funds Description',
        type: 'textarea',
        placeholder: 'Provide milestone details, e.g. 45% model training & infra, 30% GTM & pilots, 25% talent.',
      },
      {
        id: 'investorPreferences',
        label: 'Investor Preference',
        type: 'multi_select',
        options: [
          'Angel Investor',
          'Angel Network',
          'Micro VC',
          'VC Fund',
          'Family Office',
          'Corporate VC',
          'Strategic Investor',
          'Impact Investor',
          'Institutional Investor',
          'Debt Fund',
          'Government-backed Fund',
          'Any Suitable Investor',
        ],
      },
      {
        id: 'sharePitchDeck',
        label: 'Include Pitch Deck with this Ask',
        type: 'boolean',
        defaultValue: true,
        halfWidth: true,
      },
      {
        id: 'shareElevatorVideo',
        label: 'Include Elevator Pitch Video',
        type: 'boolean',
        defaultValue: true,
        halfWidth: true,
      },
      {
        id: 'shareFinancialSnapshot',
        label: 'Share Financial Snapshot',
        type: 'boolean',
        defaultValue: false,
        halfWidth: true,
      },
      {
        id: 'allowDdLockerRequest',
        label: 'Allow Direct DD Locker Requests',
        type: 'boolean',
        defaultValue: true,
        halfWidth: true,
      },
    ],
  },

  mentorship: {
    id: 'mentorship',
    label: 'Mentorship',
    description: 'Find experienced mentors and domain experts for strategic or technical advisory.',
    titlePlaceholder: 'e.g. Looking for Enterprise GTM & SOC2 Sales Advisor',
    defaultTargetUserTypes: ['Mentor'],
    responseActions: ['Offer Mentorship', 'Request Meeting', 'Send Message'],
    fields: [
      {
        id: 'mentorType',
        label: 'Mentor Type',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Venture Mentor', 'Domain Expert', 'Either'],
      },
      {
        id: 'mentorshipArea',
        label: 'Mentorship Area',
        type: 'select',
        required: true,
        halfWidth: true,
        options: [
          'Business Strategy',
          'Fundraising',
          'Product',
          'Technology',
          'Sales',
          'Marketing',
          'Go-To-Market',
          'Finance',
          'Legal',
          'Operations',
          'Leadership',
          'Hiring',
          'International Expansion',
          'Pitching',
          'Customer Discovery',
          'Product-Market Fit',
          'Other',
        ],
      },
      {
        id: 'currentChallenge',
        label: 'Current Challenge',
        type: 'textarea',
        required: true,
        placeholder: 'Describe your core bottleneck or roadblock...',
      },
      {
        id: 'expectedOutcome',
        label: 'Expected Mentorship Outcome',
        type: 'textarea',
        required: true,
        placeholder: 'What tangible milestone do you want to accomplish together?',
      },
      {
        id: 'duration',
        label: 'Mentorship Duration',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['One-Time Consultation', '1 Month', '3 Months', '6 Months', 'Custom'],
      },
      {
        id: 'customDuration',
        label: 'Custom Duration',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. 2 months intensive or quarterly reviews',
        dependsOn: { field: 'duration', value: 'Custom' },
      },
      {
        id: 'meetingFrequency',
        label: 'Meeting Frequency',
        type: 'select',
        halfWidth: true,
        options: ['Weekly', 'Bi-weekly', 'Monthly', 'As Needed'],
      },
      {
        id: 'preferredStartDate',
        label: 'Preferred Start Date',
        type: 'date',
        halfWidth: true,
      },
      {
        id: 'meetingMode',
        label: 'Meeting Mode',
        type: 'select',
        halfWidth: true,
        options: ['Virtual (Video Calls)', 'In-Person', 'Hybrid'],
      },
      {
        id: 'mentorshipBudget',
        label: 'Mentorship Budget / Compensation',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. Equity Advisory (0.25%-0.5%) or Hourly Stipend or Pro Bono',
      },
      {
        id: 'preferredMentorExperience',
        label: 'Preferred Mentor Experience',
        type: 'text',
        placeholder: 'e.g. Ex-Founder or 10+ yrs scaling B2B SaaS in Fintech',
      },
    ],
  },

  incubation: {
    id: 'incubation',
    label: 'Incubation',
    description: 'Apply for physical or virtual incubation support, lab access, and foundational mentoring.',
    titlePlaceholder: 'e.g. Seeking DeepTech Hardware & Rapid Prototyping Incubation',
    defaultTargetUserTypes: ['ESP', 'Institution'],
    responseActions: ['Offer Incubation', 'Request Meeting', 'Send Message'],
    fields: [
      {
        id: 'incubationType',
        label: 'Incubation Type',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Physical Incubation', 'Virtual Incubation', 'Hybrid Incubation', 'Academic / University Hub'],
      },
      {
        id: 'supportRequired',
        label: 'Support Required',
        type: 'textarea',
        required: true,
        placeholder: 'Specify mentoring, laboratory equipment, compliance support, office space...',
      },
      {
        id: 'preferredLocation',
        label: 'Preferred Location / City',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. Bengaluru, Hyderabad, Delhi NCR, Singapore',
      },
      {
        id: 'preferredSector',
        label: 'Preferred Sector Focus',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. DeepTech, BioTech, CleanTech, Enterprise AI',
      },
      {
        id: 'preferredDuration',
        label: 'Preferred Duration',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. 6 Months / 12 Months',
      },
      {
        id: 'infrastructureRequirements',
        label: 'Infrastructure Requirements',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. Clean room, high-performance GPU clusters, wet lab',
      },
      {
        id: 'fundingRequirement',
        label: 'Funding Requirement from Incubator',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. Seed grant, prototype stipend, or None (Resource only)',
      },
      {
        id: 'preferredStartDate',
        label: 'Preferred Start Date',
        type: 'date',
        halfWidth: true,
      },
      {
        id: 'physicalPresenceRequired',
        label: 'Physical Presence Feasible?',
        type: 'select',
        halfWidth: true,
        options: ['Yes (Full-time on-site)', 'Part-time / Hybrid', 'Virtual Only'],
      },
      {
        id: 'equityFreePreference',
        label: 'Equity-Free Preference',
        type: 'select',
        halfWidth: true,
        options: ['Equity-Free Preferred', 'Open to Standard Equity (2-4%)', 'Negotiable'],
      },
    ],
  },

  accelerator: {
    id: 'accelerator',
    label: 'Accelerator',
    description: 'Join growth accelerator cohorts with structured demo days and institutional syndicates.',
    titlePlaceholder: 'e.g. Applying for Scale-up Accelerator Cohort 2026',
    defaultTargetUserTypes: ['ESP', 'Institution'],
    responseActions: ['Invite to Program', 'Request Meeting', 'Send Message'],
    fields: [
      {
        id: 'acceleratorFocus',
        label: 'Accelerator Focus',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Enterprise SaaS', 'DeepTech & AI', 'FinTech', 'Climate & Sustainability', 'HealthTech', 'General Tech'],
      },
      {
        id: 'programDuration',
        label: 'Preferred Program Duration',
        type: 'select',
        halfWidth: true,
        options: ['8 Weeks', '12 Weeks (3 Months)', '16 Weeks', '6 Months'],
      },
      {
        id: 'preferredGeography',
        label: 'Preferred Geography',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. India, US, Southeast Asia, Global',
      },
      {
        id: 'fundingExpected',
        label: 'Funding Expected?',
        type: 'select',
        halfWidth: true,
        options: ['Yes', 'No', 'Optional'],
      },
      {
        id: 'minFundingExpected',
        label: 'Minimum Funding Expected',
        type: 'currency',
        halfWidth: true,
        placeholder: 'e.g. 5000000',
        dependsOn: { field: 'fundingExpected', value: 'Yes' },
      },
      {
        id: 'equityFreePreferred',
        label: 'Equity-Free Preferred?',
        type: 'select',
        halfWidth: true,
        options: ['Yes (Non-dilutive)', 'Open to standard cohort equity (5-7%)', 'Flexible'],
      },
      {
        id: 'demoDayAccess',
        label: 'Demo Day Access Required',
        type: 'boolean',
        defaultValue: true,
        halfWidth: true,
      },
      {
        id: 'investorAccess',
        label: 'Tier-1 Investor Access Required',
        type: 'boolean',
        defaultValue: true,
        halfWidth: true,
      },
      {
        id: 'corporateAccess',
        label: 'Corporate Pilot Access Required',
        type: 'boolean',
        defaultValue: true,
        halfWidth: true,
      },
      {
        id: 'preferredStartDate',
        label: 'Preferred Start Date',
        type: 'date',
        halfWidth: true,
      },
    ],
  },

  corporate_pilot: {
    id: 'corporate_pilot',
    label: 'Corporate Pilot',
    description: 'Pitch your enterprise solution for proof-of-concept trials with enterprise partners.',
    titlePlaceholder: 'e.g. Paid Pilot: Automated Agentic Compliance for Private Banking',
    defaultTargetUserTypes: ['ESP', 'Institution', 'Startup'],
    responseActions: ['Express Pilot Interest', 'Request Proposal', 'Schedule Meeting', 'Send Message'],
    fields: [
      {
        id: 'pilotTitle',
        label: 'Pilot / Use Case Title',
        type: 'text',
        required: true,
        placeholder: 'e.g. Multi-agent Telemetry Integration for Logistics Fleet',
      },
      {
        id: 'pilotObjective',
        label: 'Pilot Objective',
        type: 'textarea',
        required: true,
        placeholder: 'What business problem does this pilot resolve for the corporate partner?',
      },
      {
        id: 'targetIndustry',
        label: 'Target Industry',
        type: 'select',
        required: true,
        halfWidth: true,
        options: [
          'Banking & Financial Services (BFSI)',
          'Healthcare & Life Sciences',
          'Retail & E-commerce',
          'Manufacturing & Supply Chain',
          'Telecom & Media',
          'Energy & Utilities',
          'Information Technology',
          'Government & Public Sector',
          'Other',
        ],
      },
      {
        id: 'targetCorporateType',
        label: 'Target Corporate Type',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. Fortune 500 Enterprises, Mid-market B2B, Tier-1 Banks',
      },
      {
        id: 'productReadiness',
        label: 'Product Readiness Level',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Concept', 'Prototype', 'MVP', 'Live with Beta Users', 'Enterprise-Ready / Production'],
      },
      {
        id: 'pilotScope',
        label: 'Pilot Scope',
        type: 'textarea',
        required: true,
        placeholder: 'Define boundaries: number of seats, test transaction volume, sandbox vs production...',
      },
      {
        id: 'pilotDuration',
        label: 'Pilot Duration',
        type: 'select',
        halfWidth: true,
        options: ['30 Days', '60 Days', '90 Days', '6 Months'],
      },
      {
        id: 'deploymentMode',
        label: 'Deployment Mode',
        type: 'select',
        halfWidth: true,
        options: ['Cloud (SaaS)', 'On-Premise / VPC', 'Hybrid', 'API / SDK'],
      },
      {
        id: 'deploymentLocation',
        label: 'Deployment Location',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. India or Global Cloud Region',
      },
      {
        id: 'integrationRequirements',
        label: 'Integration Requirements',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. REST API, Webhooks, Single Sign-On (SAML/Okta)',
      },
      {
        id: 'expectedPilotBudget',
        label: 'Expected Pilot Budget',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. Paid POC (₹5L - ₹15L) or Zero-cost Sandbox Trial',
      },
      {
        id: 'successMetrics',
        label: 'Success Metrics (KPIs)',
        type: 'textarea',
        placeholder: 'e.g. 40% reduction in processing time, 99.5% classification accuracy',
      },
      {
        id: 'preferredStartDate',
        label: 'Preferred Pilot Start Date',
        type: 'date',
        halfWidth: true,
      },
    ],
  },

  strategic_partnership: {
    id: 'strategic_partnership',
    label: 'Strategic Partnership',
    description: 'Forge co-selling, distribution, technology integration, or joint venture alliances.',
    titlePlaceholder: 'e.g. Co-Selling & Distribution Alliance with Cloud MSPs',
    defaultTargetUserTypes: ['Startup', 'Investor', 'ESP', 'Institution'],
    responseActions: ['Propose Partnership', 'Schedule Meeting', 'Send Message'],
    fields: [
      {
        id: 'partnershipType',
        label: 'Partnership Type',
        type: 'select',
        required: true,
        halfWidth: true,
        options: [
          'Distribution',
          'Channel Partnership',
          'Co-Selling',
          'Technology Integration',
          'Manufacturing',
          'Supply Chain',
          'Licensing',
          'Joint Venture',
          'White Labelling',
          'Business Development',
          'Data Partnership',
          'Product Partnership',
          'Marketing Partnership',
          'Strategic Alliance',
          'Other',
        ],
      },
      {
        id: 'partnershipObjective',
        label: 'Partnership Objective',
        type: 'textarea',
        required: true,
        placeholder: 'What mutual synergy or strategic advantage does this partnership unlock?',
      },
      {
        id: 'whatWeOffer',
        label: 'What We Offer',
        type: 'textarea',
        required: true,
        placeholder: 'Our core technology, client base, proprietary datasets, or revenue share...',
      },
      {
        id: 'whatWeAreLookingFor',
        label: 'What We Are Looking For',
        type: 'textarea',
        required: true,
        placeholder: 'Partner enterprise relationships, distribution networks, technical capabilities...',
      },
      {
        id: 'targetPartnerType',
        label: 'Target Partner Type',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. Tier-1 System Integrators, Enterprise SaaS Vendors',
      },
      {
        id: 'commercialModel',
        label: 'Commercial Model',
        type: 'select',
        halfWidth: true,
        options: ['Revenue Share (20/80)', 'Referral Fee', 'License Fee', 'Barter / Strategic Synergy', 'Custom'],
      },
      {
        id: 'targetGeography',
        label: 'Target Geography',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. India, APAC, North America, Europe',
      },
      {
        id: 'expectedDuration',
        label: 'Expected Partnership Duration',
        type: 'select',
        halfWidth: true,
        options: ['1 Year', '2 Years', '3+ Years', 'Project-based'],
      },
      {
        id: 'partnershipReadiness',
        label: 'Partnership Readiness',
        type: 'select',
        halfWidth: true,
        options: ['Ready Immediately', 'In Development (Available next quarter)', 'Exploratory Discussion'],
      },
      {
        id: 'preferredStartDate',
        label: 'Preferred Start Date',
        type: 'date',
        halfWidth: true,
      },
    ],
  },

  research_partnership: {
    id: 'research_partnership',
    label: 'Research Partnership',
    description: 'Collaborate with university labs, R&D institutes, or scientists on deep tech innovation.',
    titlePlaceholder: 'e.g. Joint R&D on Sub-50ms Multi-Agent Consensus Mechanisms',
    defaultTargetUserTypes: ['ESP', 'Institution', 'Mentor'],
    responseActions: ['Express Research Interest', 'Request Meeting', 'Send Message'],
    fields: [
      {
        id: 'researchArea',
        label: 'Research Area',
        type: 'text',
        required: true,
        halfWidth: true,
        placeholder: 'e.g. Distributed LLM Inference, Quantum Cryptography',
      },
      {
        id: 'trl',
        label: 'Technology Readiness Level (TRL)',
        type: 'select',
        halfWidth: true,
        options: [
          'TRL 1 — Basic principles observed',
          'TRL 2 — Technology concept formulated',
          'TRL 3 — Proof of concept',
          'TRL 4 — Component validation in lab',
          'TRL 5 — Validation in relevant environment',
          'TRL 6 — Prototype demonstration',
          'TRL 7 — System demonstration in operational environment',
          'TRL 8 — System complete and qualified',
          'TRL 9 — Proven in operational environment',
        ],
      },
      {
        id: 'researchProblem',
        label: 'Research Problem / Objective',
        type: 'textarea',
        required: true,
        placeholder: 'Detail the scientific challenge or algorithmic bottleneck to solve...',
      },
      {
        id: 'researchStage',
        label: 'Research Stage',
        type: 'select',
        halfWidth: true,
        options: ['Early Ideation', 'Theoretical Formulation', 'Lab Prototyping', 'Field Testing'],
      },
      {
        id: 'partnerRequired',
        label: 'Partner Required',
        type: 'text',
        required: true,
        halfWidth: true,
        placeholder: 'e.g. University CS Department, National Research Lab, PhD Fellows',
      },
      {
        id: 'expertiseRequired',
        label: 'Expertise Required',
        type: 'text',
        placeholder: 'e.g. Formal verification of concurrent systems, model pruning algorithms',
      },
      {
        id: 'facilitiesRequired',
        label: 'Facilities Required',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. Specialized hardware labs, GPU clusters, clean room',
      },
      {
        id: 'ipStatus',
        label: 'Current IP Status',
        type: 'select',
        halfWidth: true,
        options: ['Patent Filed', 'Patent Granted', 'Trade Secret', 'Open Source', 'None'],
      },
      {
        id: 'fundingRequired',
        label: 'Funding / Co-Investment Required',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. ₹25L Co-funding or Grant-supported',
      },
      {
        id: 'researchDuration',
        label: 'Research Duration',
        type: 'select',
        halfWidth: true,
        options: ['6 Months', '12 Months', '18 Months', '24 Months'],
      },
      {
        id: 'publicationExpectations',
        label: 'Publication Expectations',
        type: 'select',
        halfWidth: true,
        options: ['Joint Academic Papers (NeurIPS, ICML)', 'Industry Whitepaper', 'Proprietary Only (No Publication)'],
      },
      {
        id: 'ipOwnership',
        label: 'IP Ownership Preference',
        type: 'select',
        halfWidth: true,
        options: ['Exclusive Startup Ownership', 'Joint Ownership with Royalty', 'Open Source with Commercial License'],
      },
      {
        id: 'targetStartDate',
        label: 'Target Start Date',
        type: 'date',
        halfWidth: true,
      },
    ],
  },

  institution_partnership: {
    id: 'institution_partnership',
    label: 'Institution Partnership',
    description: 'Partner with universities, science councils, and government innovation departments.',
    titlePlaceholder: 'e.g. University AI Lab Co-Development & Student Talent Pipeline',
    defaultTargetUserTypes: ['ESP', 'Institution'],
    responseActions: ['Propose Institution Partnership', 'Schedule Meeting', 'Send Message'],
    fields: [
      {
        id: 'institutionType',
        label: 'Institution Type',
        type: 'select',
        required: true,
        halfWidth: true,
        options: [
          'Central / State University',
          'Autonomous Technical Institute (IIT/NIT/IIIT)',
          'Research Council (CSIR/ICMR/DST)',
          'Industry Association (NASSCOM/CII/FICCI)',
          'Government Innovation Cell',
          'Other',
        ],
      },
      {
        id: 'targetDepartment',
        label: 'Target Department / Center',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. Department of Computer Science / Center for AI',
      },
      {
        id: 'partnershipObjective',
        label: 'Partnership Objective',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the shared institutional milestone or innovation impact...',
      },
      {
        id: 'proposedEngagement',
        label: 'Proposed Engagement',
        type: 'textarea',
        required: true,
        placeholder: 'e.g. Student internships, sponsored thesis, joint hackathon, guest lectures...',
      },
      {
        id: 'whatStartupProvides',
        label: 'What the Startup Provides',
        type: 'textarea',
        required: true,
        placeholder: 'e.g. Free enterprise API access, industry mentorship, sponsored stipends...',
      },
      {
        id: 'supportRequiredFromInstitution',
        label: 'Support Required From Institution',
        type: 'textarea',
        required: true,
        placeholder: 'e.g. Lab space, faculty validation, student research cohorts...',
      },
      {
        id: 'studentInvolvement',
        label: 'Student / Faculty Involvement',
        type: 'select',
        halfWidth: true,
        options: ['Faculty Advisory Only', 'Postgrad / PhD Researchers', 'Undergrad Interns', 'Full Departmental'],
      },
      {
        id: 'mouRequired',
        label: 'MoU Required?',
        type: 'select',
        halfWidth: true,
        options: ['Formal MoU Mandatory', 'Letter of Intent (LoI)', 'Informal Collaboration'],
      },
      {
        id: 'preferredGeography',
        label: 'Preferred Geography',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. Karnataka, Telangana, Tamil Nadu, Pan-India',
      },
      {
        id: 'partnershipDuration',
        label: 'Partnership Duration',
        type: 'select',
        halfWidth: true,
        options: ['1 Academic Year', '2 Academic Years', '3+ Years', 'Perpetual'],
      },
      {
        id: 'targetStartDate',
        label: 'Target Start Date',
        type: 'date',
        halfWidth: true,
      },
    ],
  },

  market_access: {
    id: 'market_access',
    label: 'Market Access',
    description: 'Tap mentor, investor, and ecosystem networks for introductions and expansion channels.',
    titlePlaceholder: 'e.g. Seeking GTM Introductions to Head of IT at UAE Financial Institutions',
    defaultTargetUserTypes: ['Mentor', 'Investor', 'ESP', 'Startup', 'Institution'],
    responseActions: ['Offer Introduction', 'Propose Market Access Support', 'Schedule Meeting', 'Send Message'],
    fields: [
      {
        id: 'targetMarket',
        label: 'Target Market',
        type: 'text',
        required: true,
        halfWidth: true,
        placeholder: 'e.g. GCC Enterprise Banking or Tier-1 US Healthcare Providers',
      },
      {
        id: 'targetGeography',
        label: 'Target Geography',
        type: 'text',
        required: true,
        halfWidth: true,
        placeholder: 'e.g. UAE & Saudi Arabia, Southeast Asia, US East Coast',
      },
      {
        id: 'targetCustomerType',
        label: 'Target Customer Type',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. CIOs, Heads of Procurement, Chief Digital Officers',
      },
      {
        id: 'targetIndustry',
        label: 'Target Industry',
        type: 'select',
        halfWidth: true,
        options: [
          'Fintech & Banking',
          'Healthcare & Hospitals',
          'Retail & D2C',
          'Logistics & Supply Chain',
          'Manufacturing',
          'Real Estate & PropTech',
          'GovTech',
          'Other',
        ],
      },
      {
        id: 'marketAccessRequired',
        label: 'Market Access Required',
        type: 'textarea',
        required: true,
        placeholder: 'Explain specifically: introductions, channel partner onboarding, distributor network...',
      },
      {
        id: 'existingTraction',
        label: 'Existing Market Traction',
        type: 'text',
        placeholder: 'e.g. 12 paying customers in India, ₹45L ARR, 99.2% customer retention',
      },
      {
        id: 'typicalDealSize',
        label: 'Typical Deal Size / ACV',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. $15,000 - $40,000 Annual Contract Value',
      },
      {
        id: 'productReadiness',
        label: 'Product Readiness Level',
        type: 'select',
        halfWidth: true,
        options: ['Production Enterprise Ready', 'Live Beta', 'Custom Integration Required'],
      },
      {
        id: 'preferredPartnerType',
        label: 'Preferred Partner Type',
        type: 'select',
        halfWidth: true,
        options: ['Ecosystem Mentor with Regional Network', 'Institutional Investor with Portfolio Cos', 'Regional Distributor / Reseller', 'Trade Commission / Embassy'],
      },
      {
        id: 'expectedOutcome',
        label: 'Expected Outcome',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. 3 qualified POC discussions within 60 days',
      },
      {
        id: 'targetTimeline',
        label: 'Target Timeline',
        type: 'select',
        halfWidth: true,
        options: ['Immediate (Next 30 days)', 'Q1 2027', 'Q2 2027', 'Flexible'],
      },
    ],
  },

  technology_support: {
    id: 'technology_support',
    label: 'Technology Support',
    description: 'Solve complex architectural, cloud infrastructure, or cybersecurity challenges.',
    titlePlaceholder: 'e.g. Need Senior Distributed Systems Architect for Consensus Latency Audit',
    defaultTargetUserTypes: ['Mentor', 'Startup', 'ESP', 'Institution'],
    responseActions: ['Offer Technical Support', 'Request Technical Discussion', 'Send Message'],
    fields: [
      {
        id: 'technologyArea',
        label: 'Technology Area',
        type: 'select',
        required: true,
        halfWidth: true,
        options: [
          'Distributed Systems & Architecture',
          'Artificial Intelligence & LLMs',
          'Cybersecurity & Pen-testing',
          'DevOps & Kubernetes Cloud Infra',
          'Blockchain & Smart Contracts',
          'Mobile (React Native / Flutter)',
          'Frontend Performance & Web Vitals',
          'Database Sharding & Query Optimization',
          'Compliance (SOC2 / HIPAA / ISO27001)',
          'Other',
        ],
      },
      {
        id: 'engagementType',
        label: 'Engagement Type',
        type: 'select',
        halfWidth: true,
        options: ['One-time Architecture Audit', 'Sprint Support (2-4 Weeks)', 'Advisory Fractional CTO', 'Codebase Review'],
      },
      {
        id: 'technicalProblem',
        label: 'Technical Problem / Bottleneck',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the bug, scale issue, architectural decision, or security gap...',
      },
      {
        id: 'supportRequired',
        label: 'Support Required',
        type: 'textarea',
        required: true,
        placeholder: 'Specify deliverables: code review, benchmark report, Terraform configs, architecture diagram...',
      },
      {
        id: 'currentTechStack',
        label: 'Current Technology / Stack',
        type: 'text',
        placeholder: 'e.g. Next.js 14, Node.js, Go, PostgreSQL, Redis, AWS ECS, Docker',
      },
      {
        id: 'requiredDeliverable',
        label: 'Required Deliverable',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. Audited system design document + GitHub PR',
      },
      {
        id: 'requiredExpertise',
        label: 'Required Expertise Level',
        type: 'select',
        halfWidth: true,
        options: ['Staff / Principal Engineer (10+ Yrs)', 'Senior Engineer (5-8 Yrs)', 'Security Certified Auditor', 'Cloud Certified Architect'],
      },
      {
        id: 'budget',
        label: 'Budget for Engagement',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. ₹50,000 - ₹1,50,000 or Equity or Pro Bono',
      },
      {
        id: 'projectDuration',
        label: 'Project Duration',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. 2 Weeks / 1 Month',
      },
      {
        id: 'targetStartDate',
        label: 'Target Start Date',
        type: 'date',
        halfWidth: true,
      },
      {
        id: 'ndaRequired',
        label: 'NDA Required before Technical Disclosure?',
        type: 'boolean',
        defaultValue: true,
        notice: 'An NDA will be required before confidential technical information is shared.',
      },
      {
        id: 'techDocsAvailable',
        label: 'Technical Documentation & Architecture Specs Available?',
        type: 'boolean',
        defaultValue: true,
      },
    ],
  },
};

// ==========================================
// 2. INVESTOR ASK CONFIGURATION (10 Categories)
// ==========================================
const INVESTOR_ASK_CATEGORIES: Record<string, AskCategoryConfig> = {
  startup_sourcing: {
    id: 'startup_sourcing',
    label: 'Startup Sourcing',
    description: 'Broadcast investment thesis and invite qualified startups to submit applications.',
    titlePlaceholder: 'e.g. Seeking Pre-Seed B2B Enterprise AI & DevTools Startups in India',
    defaultTargetUserTypes: ['Startup'],
    responseActions: ['Submit Startup', 'Express Fit', 'Request Meeting', 'Send Message'],
    fields: [
      {
        id: 'investmentStage',
        label: 'Investment Stage Focus',
        type: 'multi_select',
        required: true,
        options: ['Pre-Seed', 'Seed', 'Seed+', 'Pre-Series A', 'Series A', 'Series B', 'Growth', 'Any'],
      },
      {
        id: 'targetSectors',
        label: 'Target Sectors',
        type: 'multi_select',
        required: true,
        options: [
          'Enterprise SaaS',
          'Artificial Intelligence & DeepTech',
          'FinTech & Payments',
          'Climate & CleanTech',
          'HealthTech & BioTech',
          'Consumer & D2C',
          'Supply Chain & Logistics',
          'EdTech',
          'Web3 & Infrastructure',
        ],
      },
      {
        id: 'targetSubSectors',
        label: 'Target Sub-Sectors',
        type: 'text',
        placeholder: 'e.g. Autonomous Agents, Developer Productivity, Open Source Infra',
      },
      {
        id: 'targetGeography',
        label: 'Target Geography',
        type: 'text',
        required: true,
        halfWidth: true,
        placeholder: 'e.g. India, Southeast Asia, US',
      },
      {
        id: 'minInvestmentSize',
        label: 'Minimum Cheque Size',
        type: 'currency',
        halfWidth: true,
        placeholder: 'e.g. 2500000',
      },
      {
        id: 'maxInvestmentSize',
        label: 'Maximum Cheque Size',
        type: 'currency',
        halfWidth: true,
        placeholder: 'e.g. 20000000',
      },
      {
        id: 'preferredBusinessModel',
        label: 'Preferred Business Model',
        type: 'select',
        halfWidth: true,
        options: ['B2B SaaS', 'B2B Marketplace', 'Enterprise Licenses', 'API Consumption', 'Any Scalable Model'],
      },
      {
        id: 'revenuePreference',
        label: 'Revenue / Traction Preference',
        type: 'select',
        halfWidth: true,
        options: ['Pre-Revenue with Prototype', 'Early Beta Users', '$1k - $10k MRR', '$10k+ MRR', 'Any'],
      },
      {
        id: 'startupAgePreference',
        label: 'Startup Age Preference',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. Under 2 years',
      },
      {
        id: 'leadFollowPreference',
        label: 'Lead / Follow Preference',
        type: 'select',
        halfWidth: true,
        options: ['Can Lead Rounds', 'Co-investor / Follower Only', 'Open to Both'],
      },
      {
        id: 'investmentTimeline',
        label: 'Investment Decision Timeline',
        type: 'select',
        halfWidth: true,
        options: ['2-3 Weeks (Fast Track)', '4-6 Weeks', 'Rolling Thesis'],
      },
      {
        id: 'additionalThesisNotes',
        label: 'Additional Thesis Notes & Evaluation Criteria',
        type: 'textarea',
        placeholder: 'What proprietary advantages, founder pedigree, or unit economics do you look for?',
      },
    ],
  },

  co_investment: {
    id: 'co_investment',
    label: 'Co-Investment',
    description: 'Syndicate allocation or invite co-investors into high-conviction rounds.',
    titlePlaceholder: 'e.g. Co-Investment Allocation Open: ₹50L remaining in Series A DeepTech Syndicate',
    defaultTargetUserTypes: ['Investor'],
    responseActions: ['Express Co-Investment Interest', 'Request Deal Details', 'Request Meeting', 'Send Message'],
    fields: [
      {
        id: 'roundTitle',
        label: 'Round / Opportunity Title',
        type: 'text',
        required: true,
        placeholder: 'e.g. Series A Syndicate for Enterprise Agentic Cloud',
      },
      {
        id: 'sectorContext',
        label: 'Startup / Sector Context',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. B2B SaaS / DeepTech AI',
      },
      {
        id: 'roundStage',
        label: 'Round Stage',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Pre-Seed', 'Seed', 'Pre-Series A', 'Series A', 'Series B', 'Growth'],
      },
      {
        id: 'roundSize',
        label: 'Total Round Size',
        type: 'currency',
        halfWidth: true,
        placeholder: 'e.g. 50000000',
      },
      {
        id: 'availableAllocation',
        label: 'Available Allocation for Co-Investors',
        type: 'currency',
        halfWidth: true,
        placeholder: 'e.g. 15000000',
      },
      {
        id: 'expectedChequeSize',
        label: 'Expected Cheque Size from Co-Investors',
        type: 'text',
        required: true,
        halfWidth: true,
        placeholder: 'e.g. ₹25L - ₹50L per co-investor',
      },
      {
        id: 'coInvestorType',
        label: 'Desired Co-Investor Type',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Operator Angels', 'Micro-VC Funds', 'Family Offices', 'Corporate VCs', 'Any Accredited Fund'],
      },
      {
        id: 'leadStatus',
        label: 'Lead Investor Status',
        type: 'select',
        halfWidth: true,
        options: ['We are Leading', 'Tier-1 Lead Secured', 'Looking for Lead & Co-investors'],
      },
      {
        id: 'instrument',
        label: 'Investment Instrument',
        type: 'select',
        halfWidth: true,
        options: ['CCPS', 'i-SAFE', 'CCD', 'Equity Shares', 'Convertible Note'],
      },
      {
        id: 'closingTimeline',
        label: 'Closing Timeline',
        type: 'date',
        halfWidth: true,
      },
      {
        id: 'valueAddExpected',
        label: 'Value-Add Expected from Co-Investor',
        type: 'textarea',
        placeholder: 'e.g. Sector connections, US market distribution, customer introductions...',
      },
      {
        id: 'confidentiality',
        label: 'Confidentiality Requirement',
        type: 'select',
        options: ['NDA Required before DD Access', 'Standard Teaser Open, DD Restricted', 'Full Open Syndicate'],
      },
    ],
  },

  lead_investor: {
    id: 'lead_investor',
    label: 'Lead Investor',
    description: 'Invite institutional funds to lead a round or issue a formal term sheet.',
    titlePlaceholder: 'e.g. Seeking Institutional Lead for ₹8 Cr Seed Round in SpaceTech',
    defaultTargetUserTypes: ['Investor'],
    responseActions: ['Express Lead Interest', 'Request Deal Details', 'Schedule Meeting', 'Send Message'],
    fields: [
      {
        id: 'opportunityContext',
        label: 'Investment Opportunity Context',
        type: 'textarea',
        required: true,
        placeholder: 'Outline the company, traction milestones, and rationale for an institutional lead...',
      },
      {
        id: 'fundingStage',
        label: 'Funding Stage',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Seed', 'Pre-Series A', 'Series A', 'Series B', 'Growth'],
      },
      {
        id: 'roundSize',
        label: 'Total Round Size',
        type: 'currency',
        halfWidth: true,
        placeholder: 'e.g. 80000000',
      },
      {
        id: 'leadAllocation',
        label: 'Lead Allocation Required',
        type: 'currency',
        halfWidth: true,
        placeholder: 'e.g. 40000000 - 50000000',
      },
      {
        id: 'preferredLeadType',
        label: 'Preferred Lead Investor Type',
        type: 'select',
        halfWidth: true,
        options: ['Early-Stage Institutional VC', 'Corporate VC', 'Specialist DeepTech Fund', 'Any Qualified Lead'],
      },
      {
        id: 'governanceExpectations',
        label: 'Governance & Board Expectations',
        type: 'select',
        halfWidth: true,
        options: ['1 Board Seat Offered', 'Board Observer Seat Offered', 'Advisory Role Only', 'Open to Standard VC Governance'],
      },
      {
        id: 'investmentInstrument',
        label: 'Investment Instrument',
        type: 'select',
        halfWidth: true,
        options: ['Series A Preference Shares (CCPS)', 'iSAFE', 'Convertible Notes', 'Negotiable'],
      },
      {
        id: 'expectedClosingDate',
        label: 'Expected Closing Date',
        type: 'date',
        halfWidth: true,
      },
      {
        id: 'additionalRequirements',
        label: 'Additional Requirements / Terms',
        type: 'textarea',
        placeholder: 'e.g. Minimum check size, syndication rights, follow-on pro-rata rights...',
      },
    ],
  },

  due_diligence_support: {
    id: 'due_diligence_support',
    label: 'Due Diligence Support',
    description: 'Engage specialist consultants, technical auditors, or legal advisors for portfolio evaluation.',
    titlePlaceholder: 'e.g. Technical Codebase & IP Due Diligence Support for AI Agent Venture',
    defaultTargetUserTypes: ['Mentor', 'ESP', 'Institution'],
    responseActions: ['Offer Diligence Support', 'Request Discussion', 'Send Message'],
    fields: [
      {
        id: 'diligenceArea',
        label: 'Diligence Area',
        type: 'select',
        required: true,
        halfWidth: true,
        options: [
          'Financial',
          'Legal',
          'Technical & Architecture',
          'Product & UX',
          'Market & Competitive',
          'Commercial & Sales Pipeline',
          'Founder / Team Background',
          'Cybersecurity & Pen-Testing',
          'Intellectual Property (IP)',
          'Regulatory & Compliance',
          'ESG / Impact',
          'Other',
        ],
      },
      {
        id: 'startupContext',
        label: 'Startup / Sector Context',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. Series A Healthcare AI Startup with HIPAA data pipeline',
      },
      {
        id: 'supportRequired',
        label: 'Support Required',
        type: 'textarea',
        required: true,
        placeholder: 'Specify what you need audited, e.g. codebase scan, revenue model review, cap table audit...',
      },
      {
        id: 'engagementScope',
        label: 'Engagement Scope',
        type: 'textarea',
        required: true,
        placeholder: 'Define scope, hours, expected report depth, red-flag analysis...',
      },
      {
        id: 'expectedDeliverable',
        label: 'Expected Deliverable',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. 10-page Technical Diligence Report with Risk Matrix',
      },
      {
        id: 'timeline',
        label: 'Timeline',
        type: 'select',
        halfWidth: true,
        options: ['1 Week (Urgent IC)', '2 Weeks', '3-4 Weeks'],
      },
      {
        id: 'budget',
        label: 'Budget for Diligence',
        type: 'currency',
        halfWidth: true,
        placeholder: 'e.g. 150000',
      },
      {
        id: 'ndaRequired',
        label: 'NDA Required',
        type: 'boolean',
        defaultValue: true,
        halfWidth: true,
      },
    ],
  },

  domain_expert: {
    id: 'domain_expert',
    label: 'Domain Expert',
    description: 'Find subject matter experts to evaluate specialized technologies or market dynamics.',
    titlePlaceholder: 'e.g. Expert Consultation on Semiconductor Packaging & Fabless Workflows',
    defaultTargetUserTypes: ['Mentor', 'ESP', 'Institution'],
    responseActions: ['Offer Expertise', 'Request Meeting', 'Send Message'],
    fields: [
      {
        id: 'expertiseRequired',
        label: 'Expertise Required',
        type: 'text',
        required: true,
        placeholder: 'e.g. Battery Chemistry & Solid-State Electrolytes',
      },
      {
        id: 'sector',
        label: 'Sector',
        type: 'text',
        required: true,
        halfWidth: true,
        placeholder: 'e.g. Energy Storage / EV Infrastructure',
      },
      {
        id: 'engagementType',
        label: 'Engagement Type',
        type: 'select',
        halfWidth: true,
        options: ['1-Hour Advisory Call', 'Multi-session Review', 'Retained Domain Advisor', 'Written Evaluation'],
      },
      {
        id: 'problemContext',
        label: 'Problem / Decision Context',
        type: 'textarea',
        required: true,
        placeholder: 'Explain the decision you are making or hypothesis you need validated...',
      },
      {
        id: 'expectedContribution',
        label: 'Expected Expert Contribution',
        type: 'textarea',
        required: true,
        placeholder: 'What insights or benchmark comparisons do you expect from the expert?',
      },
      {
        id: 'budget',
        label: 'Consultation Fee / Budget',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. ₹15,000 / hour or Market Standard',
      },
      {
        id: 'ndaRequired',
        label: 'NDA Required',
        type: 'boolean',
        defaultValue: true,
        halfWidth: true,
      },
    ],
  },

  portfolio_support: {
    id: 'portfolio_support',
    label: 'Portfolio Support',
    description: 'Find specialized services, mentors, or operational talent to assist existing portfolio companies.',
    titlePlaceholder: 'e.g. Seeking Fractional VP Marketing for 2 Seed-Stage B2B Portfolio Startups',
    defaultTargetUserTypes: ['Mentor', 'Startup', 'ESP', 'Institution', 'Investor'],
    responseActions: ['Offer Portfolio Support', 'Request Meeting', 'Send Message'],
    fields: [
      {
        id: 'supportArea',
        label: 'Portfolio Support Area',
        type: 'select',
        required: true,
        halfWidth: true,
        options: [
          'Hiring & Executive Search',
          'Sales & Enterprise Pipelines',
          'Marketing & Brand',
          'GTM & Product Launches',
          'Technology & Architecture',
          'Product Management',
          'Fundraising & Syndication',
          'Finance & Fractional CFO',
          'Legal & Compliance',
          'Operations & Scaling',
          'International Expansion',
          'Corporate Introductions',
          'Mentorship',
          'Other',
        ],
      },
      {
        id: 'portfolioStage',
        label: 'Portfolio Company Stage',
        type: 'select',
        halfWidth: true,
        options: ['Pre-Seed', 'Seed', 'Series A', 'Multi-Stage Portfolio'],
      },
      {
        id: 'currentChallenge',
        label: 'Current Challenge',
        type: 'textarea',
        required: true,
        placeholder: 'Detail the operational bottleneck across one or multiple portfolio companies...',
      },
      {
        id: 'supportRequired',
        label: 'Support Required',
        type: 'textarea',
        required: true,
        placeholder: 'Define what assistance you are soliciting from the ecosystem...',
      },
      {
        id: 'expectedOutcome',
        label: 'Expected Outcome',
        type: 'text',
        required: true,
        placeholder: 'e.g. 5 executive hires completed or enterprise sales playbook delivered',
      },
      {
        id: 'duration',
        label: 'Engagement Duration',
        type: 'select',
        halfWidth: true,
        options: ['1 Month', '3 Months', '6 Months', 'Ongoing Advisory'],
      },
      {
        id: 'budget',
        label: 'Budget',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. Covered by Portfolio Company or Fund Value-Add Pool',
      },
    ],
  },

  strategic_partnership: {
    id: 'strategic_partnership',
    label: 'Strategic Partnership',
    description: 'Collaborate with institutions, corporate accelerators, or co-investment platforms.',
    titlePlaceholder: 'e.g. Joint Seed Syndicate Partnership with Singapore Family Office',
    defaultTargetUserTypes: ['Startup', 'Investor', 'ESP', 'Institution'],
    responseActions: ['Propose Partnership', 'Schedule Meeting', 'Send Message'],
    fields: [
      {
        id: 'partnershipObjective',
        label: 'Partnership Objective',
        type: 'textarea',
        required: true,
        placeholder: 'What are you aiming to accomplish together?',
      },
      {
        id: 'partnerType',
        label: 'Target Partner Type',
        type: 'text',
        required: true,
        placeholder: 'e.g. Cross-border Venture Fund, Sovereign Wealth Fund, Corporate VC',
      },
      {
        id: 'whatWeOffer',
        label: 'What We Offer',
        type: 'textarea',
        required: true,
        placeholder: 'Our deal flow, co-investment rights, due diligence capacity...',
      },
      {
        id: 'whatWeNeed',
        label: 'What We Need',
        type: 'textarea',
        required: true,
        placeholder: 'Target partner co-investment capital, regional distribution, portfolio LP access...',
      },
      {
        id: 'targetGeography',
        label: 'Target Geography',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. India, US, Middle East',
      },
      {
        id: 'expectedDuration',
        label: 'Expected Duration',
        type: 'select',
        halfWidth: true,
        options: ['1 Year', '2 Years', 'Ongoing Strategic Alliance'],
      },
    ],
  },

  corporate_market_access: {
    id: 'corporate_market_access',
    label: 'Corporate / Market Access',
    description: 'Connect portfolio companies with corporate buyers and enterprise procurement leads.',
    titlePlaceholder: 'e.g. Seeking Enterprise Retail POC Introductions for 3 AI Automation Startups',
    defaultTargetUserTypes: ['Mentor', 'Investor', 'Startup', 'ESP', 'Institution'],
    responseActions: ['Offer Introduction', 'Offer Market Access', 'Schedule Meeting', 'Send Message'],
    fields: [
      {
        id: 'portfolioContext',
        label: 'Portfolio / Opportunity Context',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the portfolio companies and the products ready for enterprise trials...',
      },
      {
        id: 'targetIndustry',
        label: 'Target Industry',
        type: 'select',
        halfWidth: true,
        options: ['Retail & FMCG', 'BFSI', 'Healthcare', 'Automotive', 'Logistics', 'Manufacturing', 'Technology'],
      },
      {
        id: 'targetGeography',
        label: 'Target Geography',
        type: 'text',
        required: true,
        halfWidth: true,
        placeholder: 'e.g. India, Southeast Asia, US West Coast',
      },
      {
        id: 'accessRequired',
        label: 'Access Required',
        type: 'textarea',
        required: true,
        placeholder: 'Specify decision makers: VP Supply Chain, Head of Innovation, CTO...',
      },
      {
        id: 'introductionType',
        label: 'Introduction Type',
        type: 'select',
        halfWidth: true,
        options: ['Warm Executive Introduction', 'Pitch Event Inclusion', 'Vendor Assessment Opportunity'],
      },
      {
        id: 'timeline',
        label: 'Timeline',
        type: 'select',
        halfWidth: true,
        options: ['Immediate (Next 30 Days)', 'Q1 Next Year', 'Ongoing'],
      },
    ],
  },

  mentor_introduction: {
    id: 'mentor_introduction',
    label: 'Mentor Introduction',
    description: 'Request tailored mentor and executive advisor pairings for your portfolio founders.',
    titlePlaceholder: 'e.g. Connecting Seed Portfolio Founder with Ex-Stripe Fintech Scaler',
    defaultTargetUserTypes: ['Mentor'],
    responseActions: ['Offer Mentorship', 'Request Introduction Discussion', 'Send Message'],
    fields: [
      {
        id: 'portfolioContext',
        label: 'Portfolio / Startup Context',
        type: 'textarea',
        required: true,
        placeholder: 'Share the founder profile, stage, and specific domain challenges...',
      },
      {
        id: 'mentorshipArea',
        label: 'Mentorship Area',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Enterprise Sales', 'US Expansion', 'Product Engineering', 'Regulatory Compliance', 'Hiring Executives'],
      },
      {
        id: 'mentorExperience',
        label: 'Mentor Experience Required',
        type: 'text',
        placeholder: 'e.g. VP or C-Level operator who scaled past $10M ARR',
      },
      {
        id: 'expectedOutcome',
        label: 'Expected Outcome',
        type: 'text',
        required: true,
        placeholder: 'e.g. Monthly 1-on-1 sparring session with CEO',
      },
      {
        id: 'duration',
        label: 'Duration',
        type: 'select',
        halfWidth: true,
        options: ['3 Months', '6 Months', '12 Months', 'Ad-hoc'],
      },
    ],
  },

  esp_accelerator_partnership: {
    id: 'esp_accelerator_partnership',
    label: 'ESP / Accelerator Partnership',
    description: 'Partner with incubators, university hubs, and accelerators for demo days and deal flow.',
    titlePlaceholder: 'e.g. Investor Demo Day Access & Fast-Track IC Partnership with Top Tier Incubators',
    defaultTargetUserTypes: ['ESP', 'Institution'],
    responseActions: ['Propose Partnership', 'Schedule Meeting', 'Send Message'],
    fields: [
      {
        id: 'partnershipType',
        label: 'Partnership Type',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Exclusive Demo Day Access', 'Cohort Co-Sponsorship', 'Office Hours Mentorship', 'Investment Syndicate Access'],
      },
      {
        id: 'investmentThesis',
        label: 'Investment Thesis / Sector Focus',
        type: 'text',
        placeholder: 'e.g. DeepTech, Autonomous Agents, Clean Energy',
      },
      {
        id: 'targetStartupStage',
        label: 'Target Startup Stage',
        type: 'select',
        halfWidth: true,
        options: ['Pre-Seed Cohort', 'Seed Accelerator', 'Growth / Scale-up Programs'],
      },
      {
        id: 'investorParticipation',
        label: 'Investor Participation Offered',
        type: 'textarea',
        placeholder: 'We offer pitch evaluations, office hour slots, and guaranteed term sheet reviews for top 3 cohort startups...',
      },
      {
        id: 'demoDayParticipation',
        label: 'Demo Day Judging / Participation',
        type: 'boolean',
        defaultValue: true,
        halfWidth: true,
      },
      {
        id: 'dealFlowAccess',
        label: 'Continuous Deal Flow Telemetry Required',
        type: 'boolean',
        defaultValue: true,
        halfWidth: true,
      },
    ],
  },
};

// ==========================================
// 3. MENTOR ASK CONFIGURATION (10 Categories)
// ==========================================
const MENTOR_ASK_CATEGORIES: Record<string, AskCategoryConfig> = {
  startup_advisory: {
    id: 'startup_advisory',
    label: 'Startup Advisory Opportunity',
    description: 'Offer strategic advisory seats to high-potential startups matching your expertise.',
    titlePlaceholder: 'e.g. Senior Tech Advisor available for Pre-Seed to Series A AI Startups',
    defaultTargetUserTypes: ['Startup'],
    responseActions: ['Request Advisory Support', 'Propose Engagement', 'Schedule Meeting', 'Send Message'],
    fields: [
      {
        id: 'preferredStage',
        label: 'Preferred Startup Stage',
        type: 'multi_select',
        required: true,
        options: ['Idea / Prototype', 'Pre-Seed', 'Seed', 'Series A', 'Series B+'],
      },
      {
        id: 'areasOfExpertise',
        label: 'Areas of Expertise',
        type: 'multi_select',
        required: true,
        options: [
          'Enterprise Architecture',
          'AI & Machine Learning Systems',
          'Go-to-Market (GTM)',
          'Fundraising & Pitch Decks',
          'B2B Sales & Procurement',
          'Product Management & Discovery',
          'Talent & Leadership',
          'International Expansion',
        ],
      },
      {
        id: 'advisoryType',
        label: 'Advisory Type',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Formal FAST Advisory Board', 'Fractional Executive Advisor', 'Monthly Strategic Sparring', 'Technical Architecture Review'],
      },
      {
        id: 'timeCommitment',
        label: 'Time Commitment',
        type: 'select',
        halfWidth: true,
        options: ['2 Hours / Month', '4 Hours / Month', '8 Hours / Month', 'Custom'],
      },
      {
        id: 'compensationPreference',
        label: 'Compensation Preference',
        type: 'select',
        halfWidth: true,
        options: ['Equity Advisory (FAST 0.25% - 1.0%)', 'Retainer Fee', 'Equity + Retainer', 'Pro Bono / Ecosystem Pay-it-Forward'],
      },
      {
        id: 'preferredGeography',
        label: 'Preferred Geography',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. India, Singapore, US, Global Remote',
      },
      {
        id: 'additionalCriteria',
        label: 'Additional Criteria / What I Look For in Founders',
        type: 'textarea',
        placeholder: 'Share your background, what founders you resonate with, and your track record...',
      },
    ],
  },

  structured_mentorship: {
    id: 'structured_mentorship',
    label: 'Structured Mentorship',
    description: 'Long-term 1 / 3 / 6-month structured developmental cycles with milestones.',
    titlePlaceholder: 'e.g. Open for 2 Structured 3-Month DeepTech Mentorship Cycles',
    defaultTargetUserTypes: ['Startup'],
    responseActions: ['Request Mentorship', 'Apply for Mentorship', 'Schedule Intro Meeting', 'Send Message'],
    fields: [
      {
        id: 'mentorshipArea',
        label: 'Mentorship Area',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['B2B Sales & Enterprise GTM', 'Product-Market Fit Validation', 'DeepTech Architecture & Scaling', 'Seed Fundraising Preparation', 'Leadership & Team Building'],
      },
      {
        id: 'programDuration',
        label: 'Program Duration',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['1 Month Sprint', '3 Months Structured', '6 Months Milestone Program'],
      },
      {
        id: 'meetingFrequency',
        label: 'Meeting Frequency',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Weekly 1-on-1 (45 mins)', 'Bi-weekly (60 mins)', 'Monthly Deep Dive (90 mins)'],
      },
      {
        id: 'maxActiveMentees',
        label: 'Maximum Active Mentees Accepted',
        type: 'number',
        halfWidth: true,
        defaultValue: 2,
        placeholder: 'e.g. 2',
      },
      {
        id: 'meetingMode',
        label: 'Meeting Mode',
        type: 'select',
        halfWidth: true,
        options: ['Virtual Video Calls', 'In-Person (Bengaluru/Delhi)', 'Hybrid'],
      },
      {
        id: 'compensationPreference',
        label: 'Compensation Preference',
        type: 'select',
        halfWidth: true,
        options: ['Paid Mentorship (Standard Monthly Fee)', 'Equity (0.25% - 0.5%)', 'Pro Bono for Early-Stage'],
      },
      {
        id: 'expectedMenteeCommitment',
        label: 'Expected Mentee Commitment & Preparation',
        type: 'textarea',
        placeholder: 'Specify weekly homework, transparent metric dashboards, and attendance expectations...',
      },
    ],
  },

  board_advisor_role: {
    id: 'board_advisor_role',
    label: 'Board / Advisor Role',
    description: 'Independent director, strategic board advisor, or fractional executive positions.',
    titlePlaceholder: 'e.g. Available as Independent Board Advisor / Strategic Observer for Scale-ups',
    defaultTargetUserTypes: ['Startup', 'ESP'],
    responseActions: ['Propose Advisor Role', 'Request Discussion', 'Send Message'],
    fields: [
      {
        id: 'roleType',
        label: 'Role Type',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Advisor', 'Strategic Advisor', 'Board Advisor', 'Independent Director', 'Board Observer', 'Fractional Executive', 'Other'],
      },
      {
        id: 'expertiseOffered',
        label: 'Expertise Offered',
        type: 'textarea',
        required: true,
        placeholder: 'Highlight your corporate governance, scaling, M&A, or IPO track record...',
      },
      {
        id: 'preferredStage',
        label: 'Preferred Startup Stage',
        type: 'select',
        halfWidth: true,
        options: ['Series A', 'Series B', 'Series C+', 'Pre-IPO', 'Late Stage'],
      },
      {
        id: 'timeCommitment',
        label: 'Time Commitment',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. Quarterly Board Meetings + 2 hours monthly sparring',
      },
      {
        id: 'compensationPreference',
        label: 'Compensation Preference',
        type: 'select',
        halfWidth: true,
        options: ['Standard Board Equity (0.5% - 1.5%)', 'Board Sitting Fee + Equity', 'Retainer', 'Negotiable'],
      },
      {
        id: 'boardAvailability',
        label: 'Board Meeting Availability',
        type: 'select',
        halfWidth: true,
        options: ['Virtual Board Presence', 'In-Person Board Meetings', 'Hybrid'],
      },
    ],
  },

  domain_consulting: {
    id: 'domain_consulting',
    label: 'Domain Consulting',
    description: 'Provide high-impact consulting sprints for technical, regulatory, or business challenges.',
    titlePlaceholder: 'e.g. Enterprise Security Architecture & SOC2 Compliance Sprint Consulting',
    defaultTargetUserTypes: ['Startup', 'Investor', 'ESP'],
    responseActions: ['Request Consulting Support', 'Schedule Discussion', 'Send Message'],
    fields: [
      {
        id: 'expertiseArea',
        label: 'Expertise Area',
        type: 'text',
        required: true,
        placeholder: 'e.g. SOC2 Type II Certification, Cloud Cost Optimization',
      },
      {
        id: 'problemTypesSupported',
        label: 'Problem Types Supported',
        type: 'textarea',
        placeholder: 'What exact projects or challenges do you solve for clients?',
      },
      {
        id: 'expectedDeliverables',
        label: 'Expected Deliverables',
        type: 'text',
        placeholder: 'e.g. Comprehensive audit report, automated scripts, implementation roadmap',
      },
      {
        id: 'engagementType',
        label: 'Engagement Type',
        type: 'select',
        halfWidth: true,
        options: ['Fixed Deliverable Project', 'Time & Materials Sprint', 'Monthly Retainer'],
      },
      {
        id: 'consultingBudget',
        label: 'Consulting Fee Preference',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. ₹1,50,000 project fee or ₹10,000/hour',
      },
      {
        id: 'ndaAvailable',
        label: 'Standard NDA Available for Execution',
        type: 'boolean',
        defaultValue: true,
      },
    ],
  },

  investor_introduction: {
    id: 'investor_introduction',
    label: 'Investor Introduction',
    description: 'Bridge high-potential mentees with institutional funds and active angels.',
    titlePlaceholder: 'e.g. Facilitating Warm Seed Introductions to Tier-1 India & US DeepTech Funds',
    defaultTargetUserTypes: ['Startup', 'Investor'],
    responseActions: ['Request Investor Introduction', 'Request Meeting', 'Send Message'],
    fields: [
      {
        id: 'investorNetworkType',
        label: 'Investor Network Type',
        type: 'text',
        required: true,
        placeholder: 'e.g. Seed VCs, Angel Networks, US/APAC Cross-border Funds',
      },
      {
        id: 'introductionSupportOffered',
        label: 'Introduction Support Offered',
        type: 'textarea',
        required: true,
        placeholder: 'How do you vet and introduce startups? Pitch deck review, pitch rehearsal, warm intro email...',
      },
      {
        id: 'fundraisingStage',
        label: 'Eligible Fundraising Stage',
        type: 'select',
        halfWidth: true,
        options: ['Pre-Seed', 'Seed', 'Series A', 'All Stages'],
      },
      {
        id: 'expectedFounderReadiness',
        label: 'Expected Founder Readiness',
        type: 'text',
        placeholder: 'e.g. Proven MVP with paying customers, clean data room, verified metrics',
      },
    ],
  },

  startup_collaboration: {
    id: 'startup_collaboration',
    label: 'Startup Collaboration',
    description: 'Collaborate with innovative startups on joint tools, prototypes, or experiments.',
    titlePlaceholder: 'e.g. Seeking Early-Stage AI Startups for Open Source Orchestration Testing',
    defaultTargetUserTypes: ['Startup'],
    responseActions: ['Propose Collaboration', 'Schedule Meeting', 'Send Message'],
    fields: [
      {
        id: 'collaborationType',
        label: 'Collaboration Type',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Open Source Project', 'Developer Tooling Trial', 'Research Experiment', 'Case Study & Benchmark'],
      },
      {
        id: 'areaOfCollaboration',
        label: 'Area of Collaboration',
        type: 'text',
        required: true,
        halfWidth: true,
        placeholder: 'e.g. Agent Benchmarking, LLM Eval Pipelines',
      },
      {
        id: 'whatIOffer',
        label: 'What I Offer',
        type: 'textarea',
        required: true,
        placeholder: 'Expert mentorship, compute resources, code contributions, industry exposure...',
      },
      {
        id: 'whatIExpect',
        label: 'What I Expect',
        type: 'textarea',
        required: true,
        placeholder: 'Product feedback, data samples, co-authored case study...',
      },
    ],
  },

  research_collaboration: {
    id: 'research_collaboration',
    label: 'Research Collaboration',
    description: 'Partner on whitepapers, empirical benchmarks, or academic conference publications.',
    titlePlaceholder: 'e.g. Co-Authoring Enterprise Autonomous Agent Security Benchmark',
    defaultTargetUserTypes: ['Startup', 'ESP', 'Institution', 'Mentor'],
    responseActions: ['Express Research Interest', 'Propose Collaboration', 'Request Meeting', 'Send Message'],
    fields: [
      {
        id: 'researchArea',
        label: 'Research Area',
        type: 'text',
        required: true,
        placeholder: 'e.g. Verifiable AI Safety & Multi-Agent Telemetry',
      },
      {
        id: 'expertiseOffered',
        label: 'Expertise Offered',
        type: 'textarea',
        required: true,
        placeholder: 'My research background, publication history, methodology...',
      },
      {
        id: 'partnerRequired',
        label: 'Partner Required',
        type: 'text',
        required: true,
        placeholder: 'e.g. Startups with live telemetry data or Academic Labs',
      },
      {
        id: 'publicationInterest',
        label: 'Publication Interest',
        type: 'select',
        halfWidth: true,
        options: ['Top-Tier Conference Paper', 'Industry Standard Whitepaper', 'Blog Series & Open Source'],
      },
      {
        id: 'researchDuration',
        label: 'Research Duration',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. 3-6 Months',
      },
    ],
  },

  speaking_workshop: {
    id: 'speaking_workshop',
    label: 'Speaking / Workshop',
    description: 'Deliver keynotes, masterclasses, or hands-on bootcamps for accelerators and hubs.',
    titlePlaceholder: 'e.g. Masterclass: Closing Enterprise B2B SaaS Contracts from India to US',
    defaultTargetUserTypes: ['ESP', 'Institution', 'Startup'],
    responseActions: ['Invite to Session', 'Request Discussion', 'Send Message'],
    fields: [
      {
        id: 'topicAreas',
        label: 'Topic Areas',
        type: 'text',
        required: true,
        placeholder: 'e.g. Enterprise Sales, Fundraising from Tier-1 VCs, Product-Market Fit',
      },
      {
        id: 'sessionType',
        label: 'Session Type',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Keynote', 'Workshop', 'Masterclass', 'AMA', 'Panel', 'Webinar', 'Bootcamp', 'Training Session', 'Other'],
      },
      {
        id: 'targetAudience',
        label: 'Target Audience',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. Pre-Seed & Seed Founders, Technical Co-founders',
      },
      {
        id: 'sessionDuration',
        label: 'Session Duration',
        type: 'select',
        halfWidth: true,
        options: ['45 Minutes', '90 Minutes (Masterclass)', 'Half-Day Workshop', 'Full-Day Bootcamp'],
      },
      {
        id: 'deliveryMode',
        label: 'Online / Offline / Hybrid',
        type: 'select',
        halfWidth: true,
        options: ['Online Webinar', 'In-Person (Travel required)', 'Hybrid'],
      },
      {
        id: 'commercialPreference',
        label: 'Commercial Preference',
        type: 'select',
        halfWidth: true,
        options: ['Standard Honorarium', 'Pro Bono for Approved Non-Profit / University Hubs', 'Flexible'],
      },
    ],
  },

  esp_program_mentorship: {
    id: 'esp_program_mentorship',
    label: 'ESP / Program Mentorship',
    description: 'Serve as an official cohort mentor or demo day judge for accelerators and incubators.',
    titlePlaceholder: 'e.g. Available as Cohort Mentor for DeepTech & SaaS Accelerators',
    defaultTargetUserTypes: ['ESP', 'Institution'],
    responseActions: ['Invite as Program Mentor', 'Request Meeting', 'Send Message'],
    fields: [
      {
        id: 'programType',
        label: 'Program Type',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Incubator Cohort', 'Accelerator Program', 'Pre-Incubation Hub', 'Corporate Innovation Bootcamp'],
      },
      {
        id: 'mentoringAreas',
        label: 'Mentoring Areas',
        type: 'text',
        required: true,
        placeholder: 'e.g. 1-on-1 Office Hours, Pitch Rehearsal, Architecture Audits',
      },
      {
        id: 'preferredStage',
        label: 'Preferred Startup Stage',
        type: 'select',
        halfWidth: true,
        options: ['Idea to Prototype', 'Early Traction / Seed', 'Growth Stage'],
      },
      {
        id: 'demoDayParticipation',
        label: 'Open to Demo Day Jury / Evaluation',
        type: 'boolean',
        defaultValue: true,
        halfWidth: true,
      },
      {
        id: 'timeCommitment',
        label: 'Time Commitment',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. 4-6 hours across 8 weeks',
      },
    ],
  },

  professional_partnership: {
    id: 'professional_partnership',
    label: 'Professional Partnership',
    description: 'Partner with fellow mentors, legal firms, or venture builders for combined advisory packages.',
    titlePlaceholder: 'e.g. Joint Advisory Package: Technical Architecture + Enterprise Legal Compliance',
    defaultTargetUserTypes: ['Mentor', 'Startup', 'Investor', 'ESP', 'Institution'],
    responseActions: ['Propose Partnership', 'Schedule Meeting', 'Send Message'],
    fields: [
      {
        id: 'partnershipType',
        label: 'Partnership Type',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Co-Advisory Syndicate', 'Cross-Referral Agreement', 'Joint Course / Program', 'Other'],
      },
      {
        id: 'objective',
        label: 'Objective',
        type: 'textarea',
        required: true,
        placeholder: 'What combined offering or joint solution are you creating?',
      },
      {
        id: 'whatIOffer',
        label: 'What I Offer',
        type: 'textarea',
        required: true,
        placeholder: 'My expertise, network, content...',
      },
      {
        id: 'whatINeed',
        label: 'What I Need',
        type: 'textarea',
        required: true,
        placeholder: 'Partner legal expertise, financial modeling, or platform reach...',
      },
    ],
  },
};

// ==========================================
// 4. ESP / INCUBATOR ASK CONFIGURATION (10 Categories)
// ==========================================
const ESP_ASK_CATEGORIES: Record<string, AskCategoryConfig> = {
  startup_applications: {
    id: 'startup_applications',
    label: 'Startup Applications',
    description: 'Call for startup applications for upcoming accelerator cohorts or incubator batches.',
    titlePlaceholder: 'e.g. Applications Open: DeepTech & AI Winter Cohort 2026 (₹50L Seed Capital)',
    defaultTargetUserTypes: ['Startup'],
    responseActions: ['Apply to Program', 'Request Program Details', 'Send Message'],
    fields: [
      {
        id: 'programName',
        label: 'Program / Cohort Name',
        type: 'text',
        required: true,
        placeholder: 'e.g. T-Hub Lab32 Cohort 15 or Peak XV Surge 11',
      },
      {
        id: 'programType',
        label: 'Program Type',
        type: 'select',
        required: true,
        halfWidth: true,
        options: [
          'Pre-Incubation',
          'Incubation',
          'Accelerator',
          'Bootcamp',
          'Corporate Innovation',
          'Scale-Up',
          'International Program',
          'Sector-Specific Program',
          'Other',
        ],
      },
      {
        id: 'targetStage',
        label: 'Target Startup Stage',
        type: 'multi_select',
        required: true,
        options: ['Idea Stage', 'Proof of Concept', 'Prototype', 'Beta / Early Revenue', 'Growth'],
      },
      {
        id: 'targetSectors',
        label: 'Target Sectors',
        type: 'multi_select',
        required: true,
        options: ['DeepTech & AI', 'FinTech', 'HealthTech', 'CleanTech', 'SaaS', 'EdTech', 'Open to All Sectors'],
      },
      {
        id: 'applicationDeadline',
        label: 'Application Deadline',
        type: 'date',
        required: true,
        halfWidth: true,
      },
      {
        id: 'programStartDate',
        label: 'Program Start Date',
        type: 'date',
        halfWidth: true,
      },
      {
        id: 'programDuration',
        label: 'Program Duration',
        type: 'select',
        halfWidth: true,
        options: ['8 Weeks', '12 Weeks (3 Months)', '16 Weeks', '6 Months', '12 Months'],
      },
      {
        id: 'cohortSize',
        label: 'Cohort Size (Number of Startups)',
        type: 'number',
        halfWidth: true,
        placeholder: 'e.g. 15',
      },
      {
        id: 'fundingAvailable',
        label: 'Funding Available',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. Up to ₹50L Equity-Free Grant or $100k SAFE',
      },
      {
        id: 'equityTaken',
        label: 'Equity Taken?',
        type: 'select',
        halfWidth: true,
        options: ['Equity-Free (0%)', '2% - 4% Advisory Equity', '5% - 7% Standard Accelerator Equity'],
      },
      {
        id: 'programBenefits',
        label: 'Program Benefits',
        type: 'textarea',
        required: true,
        placeholder: 'Highlight perks: $200k cloud credits, tier-1 VC demo day, dedicated mentors, lab access...',
      },
      {
        id: 'eligibilityCriteria',
        label: 'Eligibility Criteria',
        type: 'textarea',
        required: true,
        placeholder: 'Specify incorporation rules, founder commitment, prototype requirement...',
      },
    ],
  },

  mentor_recruitment: {
    id: 'mentor_recruitment',
    label: 'Mentor Recruitment',
    description: 'Recruit seasoned founders and functional leaders to mentor cohort companies.',
    titlePlaceholder: 'e.g. Inviting B2B Enterprise Mentors for Batch 14 Startups',
    defaultTargetUserTypes: ['Mentor'],
    responseActions: ['Apply as Mentor', 'Express Interest', 'Request Meeting', 'Send Message'],
    fields: [
      {
        id: 'cohortName',
        label: 'Program / Cohort',
        type: 'text',
        required: true,
        placeholder: 'e.g. National DeepTech Accelerator Batch 2026',
      },
      {
        id: 'mentorshipAreas',
        label: 'Mentorship Areas Required',
        type: 'multi_select',
        required: true,
        options: ['B2B Sales', 'Fundraising', 'AI Architecture', 'Product Strategy', 'Regulatory Compliance', 'International GTM'],
      },
      {
        id: 'mentorType',
        label: 'Mentor Type',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Venture Mentor', 'Domain Expert', 'Operator Angel'],
      },
      {
        id: 'timeCommitment',
        label: 'Expected Time Commitment',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['2 Hours / Month', '4 Hours / Month', 'Sprint Mentorship (Weekly)'],
      },
      {
        id: 'compensation',
        label: 'Compensation / Honorarium',
        type: 'select',
        halfWidth: true,
        options: ['Paid Honorarium per Session', 'Program Advisory Pool Equity', 'Pro Bono / Community Recognition'],
      },
      {
        id: 'demoDayJury',
        label: 'Demo Day Judging Invitation Included',
        type: 'boolean',
        defaultValue: true,
        halfWidth: true,
      },
    ],
  },

  investor_partnership: {
    id: 'investor_partnership',
    label: 'Investor Partnership',
    description: 'Partner with angel networks and VC funds for demo days and co-investing.',
    titlePlaceholder: 'e.g. Investor Demo Day Partnership: 20 Vetted Seed DeepTech Startups',
    defaultTargetUserTypes: ['Investor'],
    responseActions: ['Partner as Investor', 'Request Program Details', 'Schedule Meeting', 'Send Message'],
    fields: [
      {
        id: 'partnershipObjective',
        label: 'Partnership Objective',
        type: 'textarea',
        required: true,
        placeholder: 'Detail the mutual benefit: curated deal flow for funds, seed capital for founders...',
      },
      {
        id: 'targetInvestorType',
        label: 'Target Investor Type',
        type: 'multi_select',
        required: true,
        options: ['Micro-VCs', 'Institutional Seed Funds', 'Family Offices', 'Corporate VCs', 'Angel Networks'],
      },
      {
        id: 'investorParticipation',
        label: 'Investor Participation Options',
        type: 'textarea',
        required: true,
        placeholder: 'Office hours, lead investor rights, private syndicate access, demo day jury seat...',
      },
      {
        id: 'targetSector',
        label: 'Target Sector Focus',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. AI & SaaS',
      },
      {
        id: 'demoDayDate',
        label: 'Demo Day Date',
        type: 'date',
        halfWidth: true,
      },
    ],
  },

  corporate_partnership: {
    id: 'corporate_partnership',
    label: 'Corporate Partnership',
    description: 'Invite enterprise sponsors and industry leaders for innovation challenges and pilots.',
    titlePlaceholder: 'e.g. Corporate Innovation Challenge: Co-Sponsoring Sustainable Supply Chain Pilots',
    defaultTargetUserTypes: ['Startup', 'Investor', 'Institution'],
    responseActions: ['Propose Corporate Partnership', 'Request Proposal', 'Schedule Meeting', 'Send Message'],
    fields: [
      {
        id: 'partnershipType',
        label: 'Partnership Type',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Innovation Challenge Sponsorship', 'Corporate Cohort Partner', 'POC Provider', 'Lab Infrastructure Sponsor'],
      },
      {
        id: 'targetIndustry',
        label: 'Target Industry',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Automotive & Mobility', 'Banking & Insurance', 'Energy & Utilities', 'Healthcare', 'Retail & FMCG', 'Manufacturing'],
      },
      {
        id: 'partnershipObjective',
        label: 'Partnership Objective',
        type: 'textarea',
        required: true,
        placeholder: 'Define the corporate problem statements and innovation goals...',
      },
      {
        id: 'corporateContribution',
        label: 'Corporate Contribution Required',
        type: 'textarea',
        required: true,
        placeholder: 'Sandbox data, paid pilot budgets, executive sponsorship, problem statements...',
      },
      {
        id: 'whatEspProvides',
        label: 'What ESP Provides',
        type: 'textarea',
        required: true,
        placeholder: 'Vetted startup sourcing, demo day curation, program management, IP safeguards...',
      },
    ],
  },

  program_partner: {
    id: 'program_partner',
    label: 'Program Partner',
    description: 'Collaborate with ecosystem partners for specialized curriculum, credits, and tooling.',
    titlePlaceholder: 'e.g. Cloud & Developer Credits Partnership for Incubated Startups',
    defaultTargetUserTypes: ['Startup', 'Investor', 'Mentor', 'ESP', 'Institution'],
    responseActions: ['Propose Program Partnership', 'Schedule Meeting', 'Send Message'],
    fields: [
      {
        id: 'programName',
        label: 'Program Name',
        type: 'text',
        required: true,
        placeholder: 'e.g. Annual DeepTech Acceleration Track',
      },
      {
        id: 'partnerType',
        label: 'Target Partner Type',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Cloud & Compute Provider', 'Legal & Compliance Firm', 'Financial & Banking Partner', 'Media & PR Agency'],
      },
      {
        id: 'supportRequired',
        label: 'Support Required',
        type: 'textarea',
        required: true,
        placeholder: 'What tools, workshops, or credits are needed for startups?',
      },
      {
        id: 'supportOffered',
        label: 'Support Offered in Return',
        type: 'textarea',
        required: true,
        placeholder: 'Exclusive vendor placement, direct founder access, logo on marketing collaterals...',
      },
    ],
  },

  demo_day_participation: {
    id: 'demo_day_participation',
    label: 'Demo Day Participation',
    description: 'Invite attendees, angels, press, and ecosystem leaders to your flagship showcase.',
    titlePlaceholder: 'e.g. Annual Cohort 2026 Flagship Demo Day (In-Person & Live Stream)',
    defaultTargetUserTypes: ['Investor', 'Mentor', 'Startup', 'Institution'],
    responseActions: ['Join Demo Day', 'Express Interest', 'Request Details', 'Send Message'],
    fields: [
      {
        id: 'demoDayName',
        label: 'Demo Day Name',
        type: 'text',
        required: true,
        placeholder: 'e.g. Xentro ESP Showcase & Demo Day 2026',
      },
      {
        id: 'eventDate',
        label: 'Event Date',
        type: 'date',
        required: true,
        halfWidth: true,
      },
      {
        id: 'numberOfStartups',
        label: 'Number of Startups Pitching',
        type: 'number',
        halfWidth: true,
        placeholder: 'e.g. 18',
      },
      {
        id: 'targetSectors',
        label: 'Target Sectors Showcased',
        type: 'text',
        placeholder: 'e.g. AI, SpaceTech, Climate, FinTech',
      },
      {
        id: 'participationRequired',
        label: 'Participation Required',
        type: 'multi_select',
        required: true,
        options: ['Investor Attendance', 'Jury & Evaluation', 'Media & Press Coverage', 'Keynote Speaker'],
      },
      {
        id: 'location',
        label: 'Location / Mode',
        type: 'select',
        halfWidth: true,
        options: ['In-Person (Bengaluru)', 'In-Person (Hyderabad)', 'In-Person (Delhi)', 'Virtual Stream Only', 'Hybrid'],
      },
    ],
  },

  cohort_support: {
    id: 'cohort_support',
    label: 'Cohort Support',
    description: 'Procure operational, legal, tax, or technical support for your incubated cohort.',
    titlePlaceholder: 'e.g. Seeking Legal & MCA Compliance Partner for 25 Incubated Startups',
    defaultTargetUserTypes: ['Mentor', 'Investor', 'Startup', 'Institution', 'ESP'],
    responseActions: ['Offer Cohort Support', 'Request Discussion', 'Send Message'],
    fields: [
      {
        id: 'cohortName',
        label: 'Cohort / Program',
        type: 'text',
        required: true,
        placeholder: 'e.g. State Innovation Council Batch 8',
      },
      {
        id: 'supportArea',
        label: 'Support Area',
        type: 'select',
        required: true,
        halfWidth: true,
        options: [
          'Mentorship',
          'Technical Support',
          'Legal & Compliance',
          'Finance & Accounting',
          'Fundraising Preparation',
          'GTM & Sales',
          'Marketing & Branding',
          'Product & UI/UX',
          'Cloud & DevOps',
          'Hiring & HR',
          'Research & Patent Filing',
          'Market Access',
          'Corporate Introductions',
          'Other',
        ],
      },
      {
        id: 'numberOfStartups',
        label: 'Number of Startups Requiring Support',
        type: 'number',
        halfWidth: true,
        placeholder: 'e.g. 20',
      },
      {
        id: 'requiredExpertise',
        label: 'Required Expertise / Credentials',
        type: 'textarea',
        required: true,
        placeholder: 'Specify certifications, track record with early-stage ventures...',
      },
      {
        id: 'budget',
        label: 'Budget Allocated',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. Subsidized by Institutional Grant / Direct Billing to Startups',
      },
    ],
  },

  research_institution_partnership: {
    id: 'research_institution_partnership',
    label: 'Research / Institution Partnership',
    description: 'Establish academic research exchange, joint tech transfer, or university lab agreements.',
    titlePlaceholder: 'e.g. Tech Transfer & Commercialization Alliance with National Research Labs',
    defaultTargetUserTypes: ['Institution', 'ESP', 'Mentor', 'Startup'],
    responseActions: ['Propose Research Partnership', 'Schedule Meeting', 'Send Message'],
    fields: [
      {
        id: 'partnershipType',
        label: 'Partnership Type',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Academic Tech Transfer', 'Joint R&D Program', 'Student Entrepreneurship Track', 'Shared Lab Facilities'],
      },
      {
        id: 'researchArea',
        label: 'Research / Innovation Area',
        type: 'text',
        required: true,
        halfWidth: true,
        placeholder: 'e.g. Clean Energy, Advanced Materials, AI',
      },
      {
        id: 'targetInstitutionType',
        label: 'Target Institution Type',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['IITs / NITs / Premier Institutes', 'CSIR Research Labs', 'State Technical Universities', 'Private Universities'],
      },
      {
        id: 'objective',
        label: 'Objective & Expected Impact',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the commercialization pipeline or joint patenting goals...',
      },
    ],
  },

  technology_service_partner: {
    id: 'technology_service_partner',
    label: 'Technology / Service Partner',
    description: 'Procure software licenses, cybersecurity, or prototyping vendors for your programs.',
    titlePlaceholder: 'e.g. Procuring Cloud Infrastructure & Rapid 3D Prototyping Services',
    defaultTargetUserTypes: ['Startup', 'Mentor', 'ESP', 'Institution'],
    responseActions: ['Offer Service', 'Submit Proposal', 'Schedule Discussion', 'Send Message'],
    fields: [
      {
        id: 'serviceArea',
        label: 'Service Area',
        type: 'text',
        required: true,
        placeholder: 'e.g. Rapid Hardware Prototyping or Cloud GPU Clusters',
      },
      {
        id: 'requirement',
        label: 'Problem / Requirement',
        type: 'textarea',
        required: true,
        placeholder: 'Detail the exact services required for cohort startups...',
      },
      {
        id: 'requiredCapability',
        label: 'Required Capability / Service Tier',
        type: 'text',
        required: true,
        placeholder: 'e.g. ISO 9001 certified, Enterprise SLA support',
      },
      {
        id: 'budget',
        label: 'Budget',
        type: 'text',
        halfWidth: true,
        placeholder: 'e.g. Annual contract ₹10L - ₹25L',
      },
      {
        id: 'ndaRequired',
        label: 'NDA Required',
        type: 'boolean',
        defaultValue: true,
        halfWidth: true,
      },
    ],
  },

  market_access_partner: {
    id: 'market_access_partner',
    label: 'Market Access Partner',
    description: 'Partner with trade commissions, embassies, and overseas hubs for cohort internationalization.',
    titlePlaceholder: 'e.g. Global Market Access: Singapore & GCC Soft Landing Program for Startups',
    defaultTargetUserTypes: ['Investor', 'Mentor', 'Startup', 'ESP', 'Institution'],
    responseActions: ['Offer Market Access', 'Propose Partnership', 'Schedule Meeting', 'Send Message'],
    fields: [
      {
        id: 'marketAccessType',
        label: 'Market Access Type',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['International Soft Landing', 'State Market Expansion', 'Corporate Vendor Enlistment', 'Trade Delegation'],
      },
      {
        id: 'targetMarket',
        label: 'Target Market / Region',
        type: 'text',
        required: true,
        halfWidth: true,
        placeholder: 'e.g. Singapore, UAE, Germany, US',
      },
      {
        id: 'partnerTypeRequired',
        label: 'Partner Type Required',
        type: 'select',
        required: true,
        halfWidth: true,
        options: ['Government Trade Commission', 'Overseas Accelerator / Hub', 'Cross-Border Venture Partner', 'Industry Chamber'],
      },
      {
        id: 'expectedSupport',
        label: 'Expected Support',
        type: 'textarea',
        required: true,
        placeholder: 'e.g. Visas, local entity incorporation, local angel demo days, co-working space...',
      },
    ],
  },
};

// ==========================================
// ROLE REGISTRY
// ==========================================
export const ASK_ROLE_CONFIGS: Record<UserRole, AskRoleConfig> = {
  startup: {
    role: 'startup',
    roleLabel: 'Startup',
    categories: STARTUP_ASK_CATEGORIES,
    categoryOrder: [
      'investment',
      'mentorship',
      'incubation',
      'accelerator',
      'corporate_pilot',
      'strategic_partnership',
      'research_partnership',
      'institution_partnership',
      'market_access',
      'technology_support',
    ],
  },
  investor: {
    role: 'investor',
    roleLabel: 'Investor',
    categories: INVESTOR_ASK_CATEGORIES,
    categoryOrder: [
      'startup_sourcing',
      'co_investment',
      'lead_investor',
      'due_diligence_support',
      'domain_expert',
      'portfolio_support',
      'strategic_partnership',
      'corporate_market_access',
      'mentor_introduction',
      'esp_accelerator_partnership',
    ],
  },
  mentor: {
    role: 'mentor',
    roleLabel: 'Mentor',
    categories: MENTOR_ASK_CATEGORIES,
    categoryOrder: [
      'startup_advisory',
      'structured_mentorship',
      'board_advisor_role',
      'domain_consulting',
      'investor_introduction',
      'startup_collaboration',
      'research_collaboration',
      'speaking_workshop',
      'esp_program_mentorship',
      'professional_partnership',
    ],
  },
  esp: {
    role: 'esp',
    roleLabel: 'ESP / Hub',
    categories: ESP_ASK_CATEGORIES,
    categoryOrder: [
      'startup_applications',
      'mentor_recruitment',
      'investor_partnership',
      'corporate_partnership',
      'program_partner',
      'demo_day_participation',
      'cohort_support',
      'research_institution_partnership',
      'technology_service_partner',
      'market_access_partner',
    ],
  },
  explorer: {
    role: 'explorer',
    roleLabel: 'Explorer',
    categories: {},
    categoryOrder: [],
  },
};
