from django.urls import path
from .views import (
    AdminLoginView,
    AdminOverviewView,
    AdminEntityVerifyView,
    AdminAuditLogsView,
    AdminRegistrationRequestsView,
    AdminRegistrationActionView,
    AdminRolesListView,
    AdminSwitchRoleView,
    AdminUsersListView,
    AdminUserDetailView,
    AdminEntitiesListView,
    AdminEntityDeleteView,
    AdminComplaintsListView,
    AdminComplaintDetailView,
    AdminFeedListView,
    AdminFeedPostDeleteView,
)

urlpatterns = [
    path("admin/auth/login/", AdminLoginView.as_view(), name="admin_login"),
    path("admin/overview/", AdminOverviewView.as_view(), name="admin_overview"),
    path("admin/entities/", AdminEntitiesListView.as_view(), name="admin_entities_list"),
    path("admin/entities/<str:entity_id>/", AdminEntityDeleteView.as_view(), name="admin_entity_delete"),
    path("admin/entities/<str:entity_id>/verify/", AdminEntityVerifyView.as_view(), name="admin_entity_verify"),
    path("admin/audit-logs/", AdminAuditLogsView.as_view(), name="admin_audit_logs"),
    path("admin/users/", AdminUsersListView.as_view(), name="admin_users_list"),
    path("admin/users/<str:user_id>/", AdminUserDetailView.as_view(), name="admin_user_detail"),
    path("admin/registration-requests/", AdminRegistrationRequestsView.as_view(), name="admin_registration_requests"),
    path("admin/registration-requests/<str:user_id>/action/", AdminRegistrationActionView.as_view(), name="admin_registration_action"),
    path("admin/roles/", AdminRolesListView.as_view(), name="admin_roles_list"),
    path("admin/switch-role/", AdminSwitchRoleView.as_view(), name="admin_switch_role"),
    path("admin/complaints/", AdminComplaintsListView.as_view(), name="admin_complaints_list"),
    path("admin/complaints/<str:ticket_id>/", AdminComplaintDetailView.as_view(), name="admin_complaint_detail"),
    path("admin/feed/", AdminFeedListView.as_view(), name="admin_feed_list"),
    path("admin/feed/<str:post_id>/", AdminFeedPostDeleteView.as_view(), name="admin_feed_post_delete"),
]
