from django.urls import path
from .views import (
    SignUpView,
    SignUpStep1View,
    SendSignUpOtpView,
    VerifySignUpOtpView,
    SignInView,
    SendSignInOtpView,
    VerifySignInOtpView,
    SendOtpView,
    VerifyOtpView,
    CurrentUserView,
    UpdateAccountTypeView,
    ToggleFollowView,
    UserFollowersView,
    SubmitEspRequestView,
    UserRecommendationsView,
    UserProfileDetailView,
    UpdateUserProfileView,
    UserSupportComplaintView,
    WorkspacesListView,
    RoleUpgradeView,
    EntityCreateView,
)

urlpatterns = [
    path("auth/signup/", SignUpView.as_view(), name="signup"),
    path("auth/signup/step1/", SignUpStep1View.as_view(), name="signup_step1"),
    path("auth/signup/otp/send/", SendSignUpOtpView.as_view(), name="signup_otp_send"),
    path("auth/signup/otp/verify/", VerifySignUpOtpView.as_view(), name="signup_otp_verify"),
    path("auth/signin/", SignInView.as_view(), name="signin"),
    path("auth/signin/otp/send/", SendSignInOtpView.as_view(), name="signin_otp_send"),
    path("auth/signin/otp/verify/", VerifySignInOtpView.as_view(), name="signin_otp_verify"),
    path("auth/otp/send/", SendOtpView.as_view(), name="otp_send"),
    path("auth/otp/verify/", VerifyOtpView.as_view(), name="otp_verify"),
    path("auth/me/", CurrentUserView.as_view(), name="current_user"),
    path("auth/profile/", UpdateUserProfileView.as_view(), name="update_user_profile"),
    path("users/profile/", UpdateUserProfileView.as_view(), name="users_profile"),
    path("auth/account-type/", UpdateAccountTypeView.as_view(), name="update_account_type"),
    path("users/account-type/", UpdateAccountTypeView.as_view(), name="users_account_type"),
    path("auth/esp-request/", SubmitEspRequestView.as_view(), name="esp_request"),
    path("users/<str:user_id>/follow/", ToggleFollowView.as_view(), name="toggle_follow"),
    path("users/<str:user_id>/followers/", UserFollowersView.as_view(), name="user_followers"),
    path("users/recommendations/", UserRecommendationsView.as_view(), name="user_recommendations"),
    path("users/<str:user_id>/profile/", UserProfileDetailView.as_view(), name="user_profile_detail"),
    path("users/<str:user_id>/", UserProfileDetailView.as_view(), name="user_detail"),
    path("auth/workspaces/", WorkspacesListView.as_view(), name="auth_workspaces"),
    path("roles/upgrade/", RoleUpgradeView.as_view(), name="role_upgrade"),
    path("entities/create/", EntityCreateView.as_view(), name="entity_create"),
    path("support/complaints/", UserSupportComplaintView.as_view(), name="user_support_complaints"),
    path("support/tickets/", UserSupportComplaintView.as_view(), name="user_support_tickets"),
]
